name: Update gist with WakaTime stats
on:
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b604987ecb6558772d425c6bf0b71d67
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
